### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by azjezz** [azjezz/HHEvaluation#2]
- [ ] re-run nightly builds using a cron job every 12 hours ( ref: https://hhvm.com/api/build-status/nightly )
- [x] re-design the UI
- [ ] remove "latest"
- [ ] ability to edit existing code samples ( in case of a type, you can edit/run the script again instead of copying, and going back to home page to submit again )
